services:
  - type: web
    name: n8n-service
    plan: free

    # ← 여기를 image → node 로 바꿉니다
    runtime: node

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user

      # n8n이 커스텀 노드를 찾는 디렉토리를 명시
      - key: N8N_CUSTOM_NODES
        value: /home/node/.n8n/custom/nodes

    buildCommand: |
      # 1) n8n 본체 설치
      npm install

      # 2) 커스텀 노드 클론 & 빌드
      mkdir -p /home/node/.n8n/custom/nodes
      git clone https://github.com/GiHnHn/n8n-nodes-youtube-transcript.git /home/node/.n8n/custom/nodes/n8n-nodes-youtube-transcript
      cd /home/node/.n8n/custom/nodes/n8n-nodes-youtube-transcript
      npm install
      npm run build

    # 코드 베이스를 담은 채로 n8n을 시작
    startCommand: n8n start

databases:
  - name: n8n-db
    plan: free
