name: Build & Publish n8n Custom Image

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

env:
  IMAGE_NAME: gihnhn/n8n-custom   # ← 본인 Docker Hub ID/리포로 변경
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
